### ISSUE TITLE
License system hash mismatch 

### ISSUE THREAD

**Issue by grillorafael** [webbertakken/unity-builder#103]
I'm trying to follow the guide here for running the build but I'm encountering this problem

```
LICENSE SYSTEM [2020613 19:26:52] <hash> != <hash>
```

I have tried multiple versions of unity and this is my yaml

```yaml
name: Build
on: 
  pull_request: {}
  push: { branches: [master] }
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:
  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # projectPath:
          # - .
        unityVersion:
          - 2019.4.0f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          #- iOS # Build an iOS player.               
          #- Android # Build an Android .apk standalone app.
          - WebGL # WebGL.
          #- WSAPlayer # Build an Windows Store Apps player.
          #- PS4 # Build a PS4 Standalone.
          #- XboxOne # Build a Xbox One Standalone.
          #- tvOS # Build to Apple's tvOS platform.
          #- Switch # Build a Nintendo Switch player.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      # - uses: actions/cache@v1.1.0
      #   with:
      #     path: ${{ matrix.projectPath }}/Library
      #     key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
      #     restore-keys: |
      #       Library-${{ matrix.projectPath }}-
      #       Library-
      - uses: webbertakken/unity-builder@v1.0
        with:
          # projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
```
Current LTS and the previous 3 versions all have this error. Am I doing anything wrong?
