### ISSUE TITLE
(Question) Build is always dirty for me 

### ISSUE THREAD

**Issue by dogboydog** [webbertakken/unity-builder#121]
Should there be certain files excluded from consideration for "dirtiness"? I'm not sure how I can avoid ProjectSettings.asset being modified during the build since I am just using the default settings for the action. Although depending on the buildMethod specified, maybe other files like .meta files could change.

 I can just keep using allowDirtyBuild for the moment either way though, but curious of your thoughts on how folks should avoid using the parameter

**Comment by webbertakken** [comment]
If the file that's always dirty is your project settings and the reason is a mismatch between your local unity editor version and the on used in CI, then you should see the dirty warning as a warranted one; There are only a few million things that could potentially go wrong and it'll be impossible to debug without first synchronising the versions. Goes to https://github.com/webbertakken/unity-builder/issues/95.

If it is dirty because the test runner just ran before the build and the test artifacts are the cause, then the quick fix would be to add the artifacts folder to gitignore, but we can't possibly ask everyone to do that. So for this we need to find a reasonable solution. Progress on this can be tracked in https://github.com/webbertakken/unity-test-runner/issues/58

**Comment by dogboydog** [comment]
The editor version I'm using locally and the one I'm specifying for the unity-builder are the same, but good point that it could be a legitimate problem that ProjectSettings changed.  I did ignore `artifacts/` so ProjectSettings is the only file that's dirty for me.  From the diff, it seems like maybe the defaults for things like the android build version and things like that are modifying the ProjectSettings.

**Comment by webbertakken** [comment]
I don't think that is possible because these things aren't integrated in test-runner and the diff is checked before bootstrapping unity. 

I'm closing this question.

Feel free to create a bug if you have reason to believe something is indeed broken. Also feel free to reopen if you have any further questions directly related to this question.

**Comment by dogboydog** [comment]
Hmm okay. 

ProjectVersion.txt
```yaml
m_EditorVersion: 2019.4.1f1
m_EditorVersionWithRevision: 2019.4.1f1 (e6c045e14e4e)
```
GitHub workflow
``` yaml
name: Continuous Build and Test

on:
  pull_request: {}
  push: { branches: [github_actions] }

env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}

jobs:
  build:
    name: Build and test the game
    runs-on: ubuntu-latest
    
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2.3.1
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2.0.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.6
        with:
          unityVersion: 2019.4.1f1

      # Build
      - name: Build project (Windows)
        uses: webbertakken/unity-builder@ec0cde0c85272dcbb5a143a77374830c173346d4 # use logDiff changes
        with:
          unityVersion: 2019.4.1f1
          targetPlatform: StandaloneWindows64 # Build a 64-bit Windows standalone
```

No custom build or test method.  Build project (Windows) fails due to dirtiness, various changes to my ProjectSettings such as:

```
-  serializedVersion: 18
+  serializedVersion: 20
 -  runInBackground: 0
+  runInBackground: 1
 -  displayResolutionDialog: 0
+  stadiaPresentMode: 0
+  stadiaTargetFramerate: 0
```

What could I be doing to change this file? It seems like maybe it's the actions changing the file somehow, but I'm not sure how at the moment.  I haven't tried saving the build artifacts yet to see what effect these changes have, but I really don't want things like "displayResolutionDialog" being changed because we plan to have custom resolution menu in-game.  Maybe I'm missing something. Sorry to spam your repo! I am really enjoying your actions.
