### ISSUE TITLE
Native extension for Android target not found

### ISSUE THREAD

**Issue by ScareCrow95** [webbertakken/unity-builder#130]
I tried several different versions of unity, but I am getting the same error in each versions. 

[Here ](https://storage.googleapis.com/bag_files/5_Run%20webbertakkenunity-builder@6ece6447b229baedca54df3aae22.txt)is the complete log 

```
name: Build and Release CGS
on:
  push:
    branches:
      - master
      - dev/*
jobs:
  buildForAllPlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.3.7f1
        targetPlatform:
          - Android # Build an Android .apk standalone app.
          - iOS # Build an iOS player.
      #    - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
       #   - StandaloneWindows # Build a Windows standalone.
       #   - StandaloneWindows64 # Build a Windows 64-bit standalone.
        #  - StandaloneLinux64 # Build a Linux 64-bit standalone.
#          - WebGL # WebGL.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
      - uses: webbertakken/unity-builder@196fe8fc5b9d335768f6c0c051f285d0080c267e
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: builds
          androidAppBundle: true
          androidKeystoreName: user.keystore
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
      - uses: actions/upload-artifact@v1
        with:
          name: cgs-builds
          path: builds

```
```
2020-07-27T23:54:49.2953145Z Targeting platform: Android
2020-07-27T23:54:49.2971043Z Refreshing native plugins compatible for Editor in 0.01 ms, found 0 plugins.
2020-07-27T23:54:49.2976002Z Preloading 0 native plugins for Editor in 0.00 ms.
```

```
Register platform support module: /opt/Unity/Editor/Data/PlaybackEngines/LinuxStandaloneSupport/UnityEditor.LinuxStandalone.Extensions.dll
Register platform support module: /opt/Unity/Editor/Data/PlaybackEngines/AndroidPlayer/UnityEditor.Android.Extensions.dll
Registered in 0.004537 seconds.
Native extension for Android target not found
Native extension for LinuxStandalone target not found
```
