### ISSUE TITLE
Unexpected input(s) 'androidAppBundle', 'androidKeystorePass', 'androidKeyaliasName', 'androidKeyaliasPass'

### ISSUE THREAD

**Issue by Sl3dge78** [webbertakken/unity-builder#134]
Hey thank you for the action!

I run into an issue when building for android : 
```
##[warning]Unexpected input(s) 'androidAppBundle', 'androidKeystorePass', 'androidKeyaliasName', 'androidKeyaliasPass', valid inputs are ['unityVersion', 'targetPlatform', 'projectPath', 'buildName', 'buildsPath', 'buildMethod', 'versioning', 'version', 'androidVersionCode', 'customParameters']
```
And of course I get the following errors later : 
```
UnityException: Can not sign the application
Unable to sign the application; please provide passwords!

###########################
#      Build results      #
###########################

Duration: 00:00:01.9352420
Warnings: 0
Errors: 2
Size: 0 bytes

Build failed!
```

Here's my workflow command:
```
  - uses: webbertakken/unity-builder@v1.1
      with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          androidAppBundle: true  
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
```

To me it seems like i'm using the wrong version, but it's using the 1.1 so it should be good...

To note, it works perfectly for an iOs build.

Any ideas?
