### ISSUE TITLE
Custom versioning strategy - is it supposed to set app bundle?

### ISSUE THREAD

**Issue by gpiffaretti** [webbertakken/unity-builder#146]
Hey! I'm using this action and it's awesome.

I'm trying an action for handling versions and changelogs, so I want to use custom versioning strategy in the Unity Builder.

Here's part of my setup:

```   
        # Generate changelog with conventional commits
        - name: Conventional Changelog Action
          id: changelog
          uses: TriPSs/conventional-changelog-action@v3
          with:
            github-token: ${{ secrets.github_token }}
            skip-commit: "true"
            output-file: "false"

        # Build APK
        - name: Build APK with Unity
          uses: webbertakken/unity-builder@v0.10
          with:
            versioning: Custom
            version: ${{ steps.changelog.outputs.tag }}
            projectPath: ${{ matrix.projectPath }}
            unityVersion: ${{ matrix.unityVersion }}
            targetPlatform: ${{ matrix.targetPlatform }}
            buildsPath: build
            buildName: androidbuild
```

My questions are:
- Am I using the correct inputs? Docs mention the version field but there's no example.
- What is that value used for? I created APKs and the app bundle is still 0.1, which is the default value in the Unity project settings. Should this value be overriden by Unity Builder versioning? I don't understand what this is used for. I'm uploading the builds to AppCenter and later will go to the stores and I'd like them to get the version number from Unity Builder.
