### ISSUE TITLE
Build failure for v1.2, v1.1 and v1.0

### ISSUE THREAD

**Issue by betomaluje** [webbertakken/unity-builder#148]
**Bug description**
version 1.2, 1.1 and 1.0 is failing with this errors:
```
Run webbertakken/unity-builder@v1.2
  with:
    projectPath: Dual
    unityVersion: 2019.4.8f1
    targetPlatform: StandaloneOSX
    kubeContainerMemory: 800M
    kubeContainerCPU: 0.25
    kubeVolumeSize: 5Gi
    versioning: Semantic
    androidAppBundle: false
  env:
    UNITY_LICENSE: ***
##[warning]
      Library folder does not exist.
      Consider setting up caching to speed up your workflow,
      if this is not your first build.
    
##[warning]Fetch --unshallow caught: Error: Failed to run "git fetch --unshallow".
 In-command error caught: Error: There was an error when attempting to execute the process '/usr/bin/git'. This may indicate the process failed to start. Error: spawn /usr/bin/git ENOENT
##[error]Failed to run "git fetch".
 In-command error caught: Error: There was an error when attempting to execute the process '/usr/bin/git'. This may indicate the process failed to start. Error: spawn /usr/bin/git ENOENT
```

This doesn't happen if I use v0.15 (it build successfully) but this one generates an empty build (as reported on [this issue](https://github.com/webbertakken/unity-builder/issues/136)). I've tried searching for this issue but I haven't found anything

Also to mention, this error happens for all my `targetPlatforms`

**How to reproduce**

This is my config file:
```
name: Actions

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildAndTestForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - MyGame
        unityVersion:
          - 2019.4.8f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - WebGL # WebGL.
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          lfs: true
      
      # Cache
      - name: Getting cache
        uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
            Library-${{ matrix.projectPath }}-
            Library-
      
      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v1.2
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output 
      - name: Uploading artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
```

**Comment by webbertakken** [comment]
Looks to be a duplicate of https://github.com/webbertakken/unity-actions/issues/84 (or at least related)

By the way it's not like v1.0, v1.1 and v1.2 are all not working, it's related to your configuration and the image used.

Please note that you're also setting a lot of values to the defaults, including kubernetes variables that only work if you do a full k8s setup.

**Comment by webbertakken** [comment]
@betomaluje could you verify that inside your repository, the project is indeed inside a folder called MyGame and not in the root?

**Comment by betomaluje** [comment]
My project looks like this:
<img width="918" alt="Screenshot 2020-09-14 at 08 48 48" src="https://user-images.githubusercontent.com/1640449/93052824-1dc90880-f667-11ea-96f2-a22b2fde5e52.png">
what should I put in the `projectPath` then? 
```
# Build
      - name: Build project
        uses: webbertakken/unity-builder@v1.2
        with:
          projectPath: ./
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
```
