### ISSUE TITLE
Error code 139

### ISSUE THREAD

**Issue by juliansangillo** [webbertakken/unity-builder#153]
Hello. Every time my workflow tries running unity builder, docker keeps failing on exit code 139. According to google, docker throwing 139 is a segmentation fault.

For me, the issue is reproducible simply by running the action, so I am also linking my project repo and providing the workflow I was using.

![DeepinScreenshot_select-area_20200920154714](https://user-images.githubusercontent.com/44471531/93720690-a3155700-fb58-11ea-81ab-f78a18da40e0.png)

```yml
name: Unity3D
on:
  push:
    branches:
      - alpha
      - beta
      - master
  workflow_dispatch:
    branches:
      - alpha
env:
  PROJECT_PATH: ./MarloRunner
  BUILD_NAME: MarloRunner
  RELEASE_NAME: Marlo Runner
jobs:
build:
    name: Build - ${{ matrix.targetPlatform }} - Unity ver. ${{ matrix.unityVersion }}
    needs: initialize
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.1.0f1
        targetPlatform:
          - StandaloneLinux64
          #- StandaloneWindows64
          #- StandaloneWindows
          #- StandaloneOSX
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Download Config
        uses: actions/download-artifact@v2
        with:
          name: unity3d.config
      - name: Get Version
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: unity3d.config
          property: version
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: Library-${{ env.PROJECT_PATH }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ env.PROJECT_PATH }}-
            Library-
      - name: Build
        uses: webbertakken/unity-builder@v1.2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          buildsPath: bin
          projectPath: ${{ env.PROJECT_PATH }}
          buildName: ${{ env.BUILD_NAME }}
          version: ${{ steps.version.outputs.value }}
          versioning: Custom
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_NAME }}-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
          path: bin/${{ env.BUILD_NAME }}
```

https://github.com/juliansangillo/marlo-runner

Thanks!
