### ISSUE TITLE
Burst Compiler and DllNotFoundException: libdl.so

### ISSUE THREAD

**Issue by brett-estabrook** [webbertakken/unity-builder#175]
At the bottom is my build file and the log output for the relevant error

I see a few things that recommend running this: 
> sudo apt install libc6-dev-amd64 libc6-dev-i386 libncurses5
https://forum.unity.com/threads/dllnotfoundexception-libdl-so-2d-animation-package.693496/

I added a step to install those:

```
      - uses: ryankurte/action-apt@v0.2.0
        with: 
          packages: "libc6-dev libncurses5"
```
And got
```
 /usr/bin/sudo apt-get install -y libc6-dev libncurses5
Reading package lists...
Building dependency tree...
Reading state information...
libc6-dev is already the newest version (2.27-3ubuntu1.3).
libc6-dev set to manually installed.
libncurses5 is already the newest version (6.1-1ubuntu1.18.04).
libncurses5 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 52 not upgraded.
```

Here is the build file
```
name: Some Proj
on:
  push:
    branches: [features/unity-builder]
env:
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  #UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2019.4.13f1
jobs:
  build:
    #needs: [checklicense]
    #if: needs.checklicense.outputs.is_unity_license_set == 'true'    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          lfs: true
      - uses: actions/cache@v2.1.2
        with:
          path: Library
          key: Library          
      - uses: ryankurte/action-apt@v0.2.0
        with: 
          packages: "libc6-dev libncurses5"
      - name: Unity - Builder
        uses: webbertakken/unity-builder@v2.0-alpha-2
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: Android
      # Output
      - uses: actions/upload-artifact@v2.2.0
        with:
          name: Build
          path: build
```

```
Native extension for Android target not found
Native extension for LinuxStandalone target not found
Refreshing native plugins compatible for Editor in 1.53 ms, found 1 plugins.
Preloading 0 native plugins for Editor in 0.00 ms.
Fallback handler could not load library /opt/unity/Editor/Data/Mono/lib/libdl.so
Fallback handler could not load library /opt/unity/Editor/Data/Mono/lib/libdl.so
Fallback handler could not load library /opt/unity/Editor/Data/Mono/lib/libdl.so
Fallback handler could not load library /opt/unity/Editor/Data/Mono/lib/libdl.so
Fallback handler could not load library /opt/unity/Editor/Data/Mono/lib/libdl.so
Fallback handler could not load library /opt/unity/Editor/Data/Mono/lib/libdl.so
Fallback handler could not load library /opt/unity/Editor/Data/Mono/lib/libdl.so
Fallback handler could not load library /opt/unity/Editor/Data/Mono/lib/libdl.so
Fallback handler could not load library /opt/unity/Editor/Data/Mono/lib/libdl.so
DllNotFoundException: libdl.so
  at (wrapper managed-to-native) Burst.Backend.UnmanagedLibrary+UnixUnmanagedLibrary.dlopen(string,int)
  at Burst.Backend.UnmanagedLibrary+UnixUnmanagedLibrary.LoadLibrary (System.String name, System.Boolean addPlatformPrefix, System.Boolean addPlatformFileExtension) [0x0001e] in <004b2bef11fb4c94aedd2162289437e6>:0 
  at Burst.Backend.UnmanagedLibrary.LoadLibrary (System.String name, System.Boolean addPlatformPrefix, System.Boolean addPlatformFileExtension) [0x00020] in <004b2bef11fb4c94aedd2162289437e6>:0 
  at Burst.Backend.StandardCompilerBackend..ctor (System.String nativeSharedLibraryName) [0x0000d] in <004b2bef11fb4c94aedd2162289437e6>:0 
  at Burst.Backend.StandardCompilerBackend.GetSingleton (System.String backendName) [0x0001f] in <004b2bef11fb4c94aedd2162289437e6>:0 
  at Burst.Backend.StandardCompilerBackend.GetDefault () [0x00000] in <004b2bef11fb4c94aedd2162289437e6>:0 
  at Burst.Compiler.IL.Jit.JitCompilerService..ctor (System.Int32 numberOfThreads, System.String libraryCacheFolderName) [0x000c7] in <991cfc0e5dc843b2a9bb6d6c2e81a171>:0 
  at Burst.Compiler.IL.Jit.JitCompilerService..ctor () [0x00000] in <991cfc0e5dc843b2a9bb6d6c2e81a171>:0 
Unity.Burst.LowLevel.BurstCompilerService:InitializeInternal(String, ExtractCompilerFlags)
Unity.Burst.LowLevel.BurstCompilerService:Initialize(String, ExtractCompilerFlags)
Unity.Burst.Editor.BurstLoader:.cctor()
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[])
 
(Filename: <004b2bef11fb4c94aedd2162289437e6> Line: 0)

Unexpected error while trying to initialize the burst JIT compiler: Unexpected exception occured while initializing burst JitCompilerService
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
Unity.Burst.LowLevel.BurstCompilerService:Initialize(String, ExtractCompilerFlags) (at /home/bokken/buildslave/unity/build/Runtime/Export/Burst/BurstCompilerService.cs:28)
Unity.Burst.Editor.BurstLoader:.cctor() (at Library/PackageCache/com.unity.burst@1.4.1/Editor/BurstLoader.cs:126)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(IntPtr)
System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor(RuntimeTypeHandle)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[]) (at /home/bokken/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:114)
 
(Filename: /home/bokken/buildslave/unity/build/Runtime/Export/Burst/BurstCompilerService.cs Line: 28)

System.InvalidOperationException: Burst failed to compile the function pointer `Int32 DoGetCSRTrampoline()`
  at Unity.Burst.BurstCompiler.Compile[T] (T delegateObj, System.Boolean isFunctionPointer) [0x00186] in /github/workspace/Library/PackageCache/com.unity.burst@1.4.1/Runtime/BurstCompiler.cs:222 
  at Unity.Burst.BurstCompiler.CompileFunctionPointer[T] (T delegateMethod) [0x00008] in /github/workspace/Library/PackageCache/com.unity.burst@1.4.1/Runtime/BurstCompiler.cs:119 
  at Unity.Burst.Intrinsics.X86.CompileManagedCsrAccessors () [0x00001] in /github/workspace/Library/PackageCache/com.unity.burst@1.4.1/Runtime/Intrinsics/x86/Csr.cs:245 
  at Unity.Burst.Editor.BurstLoader..cctor () [0x00184] in /github/workspace/Library/PackageCache/com.unity.burst@1.4.1/Editor/BurstLoader.cs:204 
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogError(Object)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes(Type[]) (at /home/bokken/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs:118)
 
(Filename: /home/bokken/buildslave/unity/build/Editor/Mono/EditorAssemblies.cs Line: 118)
```
