### ISSUE TITLE
Personal license not recognized on alpha

### ISSUE THREAD

**Issue by GabrielBottari** [webbertakken/unity-builder#178]
**Bug description**

On the alpha channel (tested with v2.0-alpha-3 & v2.0-alpha-2), my personal unity license can't seem to be activated/confirmed. This works on v1.5 and the activation also works with [unity-activate](https://github.com/webbertakken/unity-activate).

```
[LicensingClient] ERROR Failed to connect to local IPC
[Licensing::Module] Failed to connect to channel: LicenseClient-root
[Licensing::Module] Successfully launched the LicensingClient
[LicensingClient] Timed-out attempting to connect to the Licensing Client on pipe: LicenseClient-root.
[LicensingClient] ERROR Failed to connect to local IPC
[Licensing::Module] Failed to connect to channel: LicenseClient-root
IPC channel to LicensingClient doesn't exist; falling back to Legacy licensing
[LicensingClient] ERROR Failed to disconnect local IPC connection

LICENSE SYSTEM [20201114 3:1:0] Next license update check is after 2020-11-15T01:14:07


LICENSE SYSTEM [20201114 3:1:0] 576562626572264761624c65526f7578 != 5d7a230315714e6ba9962c7e118657a1


LICENSE SYSTEM [20201114 3:1:0] 576562626572264761624c65526f7578 != 5d7a230315714e6ba9962c7e118657a1

DisplayProgressbar: Unity license
[UnityConnectServicesConfig] config is NOT valid, switching to default
[1114/030101:ERROR:browser_main_loop.cc(161)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[1114/030101:ERROR:sandbox_linux.cc(308)] InitializeSandbox() called with multiple threads in process gpu-process
Cancelling DisplayDialog: Failed to activate/update license Missing or bad username or password. Please try again using valid credentials or contact support@unity3d.com
This should not be called in batch mode. 
(Filename: ./Editor/Platform/Linux/EditorUtility.cpp Line: 274)

Build failed, with exit code 1
```

**How to reproduce**

My unity version is 2019.4.0f1

```
- name: Build
  uses: webbertakken/unity-builder@v2.0-alpha-3
  with:
    unityVersion: ${{ matrix.unity-version }}
    targetPlatform: Android
```

**Comment by webbertakken** [comment]
Did you also activate using the latest alpha version of the [Request Activation File](https://github.com/webbertakken/unity-request-activation-file) action?

**Comment by GabrielBottari** [comment]
Oh wow it did fix the issue! Thank you 👍

**Comment by luisplata** [comment]
I have this problem

```
[LicensingClient] ERROR Failed to connect to local IPC
[Licensing::Module] Failed to connect to channel: LicenseClient-root
[Licensing::Module] Successfully launched the LicensingClient
[SignatureVerifier] Application signature verification not supported on this platform.
[Licensing::Module] Successfully connected to LicensingClient on channel: LicenseClient-root
[Licensing::Module] Successfully launched and connected to LicensingClient
Entitlement-based licensing initiated
[LicensingClient] Licenses Updated successfully in LicensingClient
Desktop is 640 x 480 @ 60 Hz

LICENSE SYSTEM [20201126 15:17:3] Next license update check is after 2020-10-07T16:55:31
```
```
name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2019.4.10f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - Android # Build an Android .apk standalone app.
          - WebGL # WebGL.
```

https://github.com/luisplata/JuegoDeUnBotonParaMoviles/blob/main/.github/workflows/CompilerAndBuild.yml

https://github.com/luisplata/JuegoDeUnBotonParaMoviles/actions/runs/385888400

Fails Android only.
