### ISSUE TITLE
Passing along a configuration that worked.

### ISSUE THREAD

**Issue by cyberfox** [webbertakken/unity-builder#30]
Greetings,
After changing to the newest `unity-request-manual-activation-file@v1.1` I was able to download the right Unity version (2019.2.14f1) for my project.  The build itself still did not work, however, so I figured out how the underlying Docker images worked, and ran it locally on my Mac.  I had a similar problem that was due to LFS not working, which made me wonder if LFS was being used on the checkouts.  It turns out that's a newer feature of the checkout action, so I turned on LFS for my builds, and **_it worked_**.

This is my working build file (after removing the manual-activation step, as it's not necessary after I've set the `UNITY_LICENSE` secret).

```yml
name: Unity - Builder

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2019.2.14f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: webbertakken/unity-builder@master
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: PowerOffense-${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
```
I hope it helps as an example of what can work.

A few details; it uses `buildName` to put the apps name in the resultant build's executable.  **~It uses LFS, which...SO FAR appears to be 'free' when running on GitHub's own servers.~**  It does NOT cache the Library yet; I'll try that in a day or so.  It uses `checkout@v2`. It uses `.` as the project path, since the repo has the project in the root directory.

Anyway, thanks **VERY MUCH** for these tools, and your help getting it working!
