### ISSUE TITLE
##[error]The process '/usr/bin/docker' failed with exit code 1

### ISSUE THREAD

**Issue by BaptisteBillet** [webbertakken/unity-builder#78]
Hello, big beginner here.
I try the following things and got this error:
##[error]The process '/usr/bin/docker' failed with exit code 1

I'm not sure why or how to fix it.

```
name: Actions 😎

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><root>\n    <License id=\"Terms\">\n        <MachineBindings>\n            <Binding Key=\"1\" Value=\"d39b8e2f4d364b2e98b06afa0c6e08c5\"/>\n            <Binding Key=\"2\" Value=\"d39b8e2f4d364b2e98b06afa0c6e08c5\"/>\n        </MachineBindings>\n        <MachineID Value=\"Xxo1ZKbdPu/IATrc0mPBYANJFF0=\"/>\n        <SerialHash Value=\"1efd68fa935192b6090ac03c77d289a9f588c55a\"/>\n        <Features>\n            <Feature Value=\"33\"/>\n            <Feature Value=\"1\"/>\n            <Feature Value=\"12\"/>\n            <Feature Value=\"2\"/>\n            <Feature Value=\"24\"/>\n            <Feature Value=\"3\"/>\n            <Feature Value=\"36\"/>\n            <Feature Value=\"17\"/>\n            <Feature Value=\"19\"/>\n            <Feature Value=\"62\"/>\n        </Features>\n        <DeveloperData Value=\"AQAAAEY0LUg2WFMtUE00NS1SM0M4LUUyWlotWkdWOA==\"/>\n        <SerialMasked Value=\"F4-H6XS-PM45-R3C8-E2ZZ-XXXX\"/>\n        <StartDate Value=\"2018-05-02T00:00:00\"/>\n        <UpdateDate Value=\"2019-11-25T18:23:38\"/>\n        <InitialActivationDate Value=\"2018-05-02T14:21:28\"/>\n        <LicenseVersion Value=\"6.x\"/>\n        <ClientProvidedVersion Value=\"2019.2.11f1\"/>\n        <AlwaysOnline Value=\"false\"/>\n        <Entitlements>\n            <Entitlement Ns=\"unity_editor\" Tag=\"UnityPersonal\" Type=\"EDITOR\" ValidTo=\"9999-12-31T00:00:00\"/>\n        </Entitlements>\n    </License>\n<Signature xmlns=\"http://www.w3.org/2000/09/xmldsig#\"><SignedInfo><CanonicalizationMethod Algorithm=\"http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments\"/><SignatureMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#rsa-sha1\"/><Reference URI=\"#Terms\"><Transforms><Transform Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/></Transforms><DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/><DigestValue>JHdOBFmBNq2H8BrGFzir/StLoYo=</DigestValue></Reference></SignedInfo><SignatureValue>aENLHd37a51RtP2/g7YU0Pexf5mx0/ENXYGtrPzqwZ8NQt2AsSdxGnl0CUB45/GuNXfJVDt2HWot\ncNYZB2OylVBn1WHQbKZlPmm8gEAMz0MYbr4Isb5i5buryBrZlmbEOjnRI+pEg1CBwlgMo6xdtjjE\n/d7cC293QIUO91kdzRXftYou1dNaUyuPL9ZH65vdB2pDXGRNxgUVD+GnnqZA7b5L2HXqNQclcWAK\n5Yd1BeF3VzR1iLw9G/SmH5oOhnpXSmqbL4qk7LVP2/mgXpFk5kP4X8VC3z47obNhBIGq40dwWyEe\nUYk5/nRAOkZawDT+tcu96e06gPC9Cxk5PdbRbA==</SignatureValue></Signature></root>"

jobs:
  readmeWorkflow:
    name: Readme Workflow ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: ./Library
          key: Library-test-project-StandaloneWindows

      # Test
      #- name: Run tests
       # uses: webbertakken/unity-test-runner@v1.3
        #with:
          #unityVersion: 2019.2.11f1

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.2.11f1
          targetPlatform: StandaloneWindows

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
```

**Comment by webbertakken** [comment]
Heya @BaptisteBillet and thank you for reporting your problem! 

Unfortunately `##[error]The process '/usr/bin/docker' failed with exit code 1` only tells me that the process exited with a code that is not success (0) and nothing more. Could you please go through the log and see if there are any errors or warnings that are more descriptive?

Your configuration looks good if your Unity project resides in the root of your repository. I also see you're using my personal license, which is not intended for copy pasting into your own workflow. Lastly I see you're not using the latest version of unity-builder, feel free to upgrade that one at your convenience.

**Comment by BaptisteBillet** [comment]
Hello @webbertakken 
Thanks a lot for your answer!

Ok so, first of all, I upload my own license, sorry for the copy-paste without thinking :/

The error arrive just after those:
###########################
#    Edit Mode Results    #
###########################

cat: /github/workspace/artifacts/editmode-results.xml: No such file or directory
cat: /github/workspace/artifacts/editmode-results.xml: No such file or directory

###########################
#    Play Mode Results    #
###########################

cat: /github/workspace/artifacts/playmode-results.xml: No such file or directory
cat: /github/workspace/artifacts/playmode-results.xml: No such file or directory
##[error]The process '/usr/bin/docker' failed with exit code 1

My Unity project is on the root normally. The Assets, Library... are directly in the repository.

I also update the builder (v0.12)

I join you my logs as I still have the issue and don't understand why.

Thanks a lot for your help, it's really frustrating to don't understand why this failed.
[logs_18.zip](https://github.com/webbertakken/unity-builder/files/4396152/logs_18.zip)

**Comment by webbertakken** [comment]
In your logfile it says

```console
2020-03-27T22:14:40.0000774Z Scripts have compiler errors.
2020-03-27T22:14:40.0001399Z  
2020-03-27T22:14:40.0002037Z (Filename: ./Runtime/Utilities/Argv.cpp Line: 360)
2020-03-27T22:14:40.0002422Z 
2020-03-27T22:14:40.0002724Z 
2020-03-27T22:14:40.0003333Z Aborting batchmode due to failure:
2020-03-27T22:14:40.0004254Z Scripts have compiler errors.
2020-03-27T22:14:40.0004782Z 
2020-03-27T22:14:40.0005763Z /home/builduser/buildslave/unity/build/PlatformDependent/Linux/External/baselib/builds/Platforms/Linux/Include/PAL_ThreadLocalStorage.inl.h(12): Assertion failed (rc == 0)
2020-03-27T22:14:40.0006628Z ./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
2020-03-27T22:14:40.0007423Z ./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
2020-03-27T22:14:40.0008352Z ./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
2020-03-27T22:14:40.0009057Z ./Editor/Platform/Linux/TempStubs.cpp:PlatformImageForIconForExtension
2020-03-27T22:14:40.0009747Z ./Editor/Platform/Linux/UsbDevices.cpp:UsbDevicesQuery
```

Is this file related to your project? Note that the logs in the zip file are showing error logs of a different workflow, where it already fails in the tests (possibly for the same reason).

It looks like either some files in your project are not compiling, or something internal goes wrong because you didn't configure the test action correctly.

From what I can see in the logs is that your config looks like the one below, which looks fine to me.

```yaml
webbertakken/unity-test-runner@v1.3
  with:
    unityVersion: 2019.2.11f1
  env:
    UNITY_LICENSE: ***
```

Which leads me to believe the problem is indeed a compilation error in one of the files or plugins of your project, specifically related to `Filename: ./Runtime/Utilities/Argv.cpp` on `Line: 360`.

Remember that there are already hundreds of people successfully testing and building their projects. So either it's something in your project, or otherwise you're using a feature or plugin that noone else is using so far.

You could try to reproduce the issue on your own machine by running your tests in batchMode.
