### ISSUE TITLE
Providing an incorrect path should fail the build instead of create a build based on an empty project

### ISSUE THREAD

**Issue by betomaluje** [webbertakken/unity-builder#87]
After building my game using this Action, I can't play it when downloading the artifact. I can build it locally (and it works) but when downloading the generated artifact, it's unplayable: it just shows a black screen after the "Made with Unity" splashscreen.
Also, and maybe related, if I add an icon through Unity player settings, it doesn't work show in the downloaded artifact.
My config file is:
```
name: Actions

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  buildAndTestForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          -name-of-my-game
        unityVersion:
          - 2019.3.3f1 # same as my local Unity version
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Getting cache
        uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-   
      - name: Build project
        uses: webbertakken/unity-builder@v0.15
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Uploading artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
```
I've tried using the `unity-builder@v0.11` and `unity-builder@v0.15` and still nothing. Is it something I'm doing wrong?

**Comment by webbertakken** [comment]
@betomaluje Thanks a lot for reporthing this issue!

Personally I'm also having an issue with a shader being invisible when built through builder, but when I build it on my machine it turns out fine. I have not had time to figure out why that is.

Your issue likely is something similar where some shaders end up being transparent, making it look all black. Unfortunately I can't simply debug this with your config as we need a lot more specifics.

What might help is to get the latest 2019.3 version, but there's still a big change it's not going to fix the problem. Also note that builder is based on Linux images, so this may also be related. It's very likely that there is some setting in Unity that works for windows but not on Linux and vise versa.

Other possibilities are that some features or libraries are missing in the actual docker images, however there's no way for me to tell.

Sorry I don't have better news. Hope you could provide a lot more detail about how your project is different from a new project and perhaps discuss steps for a solution here.

**Comment by matthew17754** [comment]
I can confirm this issue as I am experiencing the exact same thing with `unity-builder@v0.10` and `unity-builder@v0.11`. A blank screen after the Unity splash screen. I am using the complete sample provided on the [marketplace](https://github.com/marketplace/actions/unity-builder).

My personal thoughts are that there's something wrong with the build path, but if that were the case then it wouldn't even compile at all right?

**Comment by webbertakken** [comment]
@betomaluje looking at your config again, your build path seems to be incorrect, as you're missing a space, i.e. `-name-of-my-game` should be `- name-of-my-game`. 

Additionally, assuming that error may have slipped in during posting it here; Can you make sure that your project is actually in a subfolder called `name-of-my-game` ?

**Comment by matthew17754** [comment]
@webbertakken Apparently the build completes successfully regardless of if a Unity project is found within the repository or not. Shouldn't that trigger a failed check? ❌ 

I consistently produce the blank screen behavior using the [complete example](https://github.com/marketplace/actions/unity-builder#complete-example). Suggestions?

**Comment by webbertakken** [comment]
@matthew17754 I believe that is an assumption you're making there. Can you confirm this as a fact? Yes if that is really the case that should trigger a failed check of course.

For the blank screen, as mentioned above:
> Unfortunately I can't simply debug this with your config as we need a lot more specifics.

This still holds true. You're free to investigate, but personally I don't have enough time in the world to test everyone's projects. Please note that there are many people successfully building their project already. It would be greatly appreciated if you could find out what the issue is with the complete example.

**Comment by matthew17754** [comment]
@webbertakken I can confirm. Here's a link to my testing [repository](https://github.com/matthew17754/unity-ci-test).

As you'll observe, I'm receiving passing checks even after removing the Unity project from the repo. ✔️ 

The build is currently being generated for Unity `2019.2.11f1`.

To confirm the blank screen issue, if you have time please take a look at the generated build [artifact](https://github.com/matthew17754/unity-ci-test/suites/689858793/artifacts/6489137).

Thank you for your quick responsiveness.

**Comment by webbertakken** [comment]
Thanks for confirming that one. Probably it will help to provide a check to see if the specified folder is indeed a unity project.

Looking through this thread, that also seems to be the only issue. I'll adjust the title.

Anyone is free to contribute a check if they feel the need for it.

**Comment by darrencperry** [comment]
hey @matthew17754 - an issue I had when I first started was that there were no scenes added to my build settings. Sorry if I'm late to this issue and you've resolved it already but it looks like your buildme project doesn't have any scenes added to the build settings. 

https://github.com/matthew17754/unity-ci-test/blob/master/buildme/ProjectSettings/EditorBuildSettings.asset

```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!1045 &1
EditorBuildSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_Scenes:
  - enabled: 0
    path: 
    guid: 00000000000000000000000000000000
  m_configObjects: {}
```

**Comment by matthew17754** [comment]
@darrencperry Thank you! That was it. ✔️  
@betomaluje I think this is the solution to your problem.

**Comment by webbertakken** [comment]
Closing this issue as it seems to be resolved.

**Comment by betomaluje** [comment]
Hi, sorry for the late answer but in my case I do have scenes on my build (I think right?)

```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!1045 &1
EditorBuildSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_Scenes:
  - enabled: 1
    path: Assets/Scenes/Menu/MainMenu.unity
    guid: cc26a58c1c390e849a32db5af20170e1
  - enabled: 1
    path: Assets/Scenes/LevelAdventure.unity
    guid: 722129650970c4142be7de1d94823afc
  - enabled: 1
    path: Assets/Scenes/LevelViking.unity
    guid: 6d2a2f2e720e2c448a5d62e6a7de3993
  - enabled: 1
    path: Assets/Scenes/AdventureLocal.unity
    guid: ab1935fc1bcb5194ea6b852eb8a24474
  m_configObjects: {}
```
