### ISSUE TITLE
Use version number in artifact file name

### ISSUE THREAD

**Issue by darrencperry** [webbertakken/unity-builder#97]
I wondered if it could be useful to have the version number returned from the build action, perhaps to append to the name of the artifact file?

```
# Build
      - name: Build project
        uses: webbertakken/unity-builder@v1.0
        id: buildRunner
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      # Output 
      - uses: actions/upload-artifact@v1
        with:
          name: Build-${{ steps.buildRunner.outputs.version}}
          path: build
```
